// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Persistance;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(SweetHomeDbContext))]
    [Migration("20260610143000_AddSmartHomeLayout")]
    partial class AddSmartHomeLayout
    {
    }
}
