server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/ssl/sweethome/selfsigned.crt;
    ssl_certificate_key /etc/ssl/sweethome/selfsigned.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    root /var/www/sweethome;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
    }

    location /Account/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
    }

    location /swagger/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
    }

    location / {
        try_files $uri /index.html;
    }
}
